### ISSUE TITLE
LaTeX commands stripping

### ISSUE THREAD

**Issue by juanfal** [titoBouzout/WordCount#49]
How to add LaTeX commands stripping?

I've tried with:

```
   ,
    "LaTeX": [
        "\\\S\\{[^\\}]\\}"
    ]
```

but it seems to not work.

**Comment by titoBouzout** [comment]
> Remove regex patterns by syntax. Use lowercase for the syntax names.

**Comment by FichteFoll** [comment]
`\\\S` is also probably not what you want.

**Comment by juanfal** [comment]
I know that a tex grammar is not so easy.  The other 

```
"strip": {
    "php": [
        "<[^>]*>"
    ],
    "html": [
        "<[^>]*>"
    ]
}
```

don't contain any backslash… What I want is this regex: "\\w+{[^}]*}"

But saving it (WordCount.sublime-settings) gives me

```
Error trying to parse settings: Invalid escape in Packages/User/WordCount.sublime-settings:29:14
```

either with " or '

Why?

**Comment by FichteFoll** [comment]
Settings files are JSON. JSON requires escaping on its own, before the string is actually built. Thus, every backslash in the regular expression needs another backslash to become an actual backslash in the string.

So, `"\\\\\\w+\\{[^}*\\}"` is what you want.

**Comment by juanfal** [comment]
Trying with

```
"strip": {
    "php": [
        "<[^>]*>"
    ],
    "html": [
        "<[^>]*>"
    ],
    "latex": [
        "\\%.*",
        "\\\\\\w+\\{[^}*\\}"
        // "\\%.*"
    ]
}
```

but it seems not to admit more than one re (tried also with simply `"(\\%.*|\\\\\\w+\\{[^}*\\})"`) and commented words are always included

Thanks anyway!  That's something

**Comment by titoBouzout** [comment]
okei the problem was that recently sublime text changed the name of the syntax files from latex.tmLanguage to latex.sublime-syntax, so this was causing to set the syntax as "latex.sublime-syntax" instead of "latex" because this package was expecting "tmLanguage" as file extension. I decided to remove everything before the first "." in the basename of the files, so I guess your last attempt should just work (after updating this package and restarting ST)

**Comment by FichteFoll** [comment]
By convention, the extension is considered to be everything after the _last_ dot in a filename, not after the first, to allow normal dots in filenames. This _likely_ won't be a problem for syntax definition file names though.

Anyway, you should probably be using `os.path.splitext(os.path.basename(syntax))[1]`.

You can circumvent user error with not providing lower-cased syntax names by lowercasing them in the code.

**Comment by titoBouzout** [comment]
Agree with the extension part, but no method is good, because tomorrow they add two dots anywhere and some of both will be broken but well.. 

As for the user-error, I do lower-case in other preferences https://github.com/titoBouzout/WordCount/blob/st3/WordCount.py#L47-L48 
but on this one I'm accessing the array index .. https://github.com/titoBouzout/WordCount/blob/st3/WordCount.py#L201-L202
so, I been lazy to normalize that preference :P pull reqests welcome :D

**Comment by FichteFoll** [comment]
Pull requests are always welcome, I suppose.

I can write a short sentence about the "issue" but even just forking and pulling the repo would probably take about the same time. And at that point I haven't even changed any code.

I don't even use this plugin. I'm just suscribed because it was once a part of the SublimeText org. That said, I'm actually unsubscribing now, so you'll have less noise from me~
